CREATE TABLE IF NOT EXISTS Insert_Queries (
    `INSERT_INTO_Doctor_doc_id` VARCHAR(42) CHARACTER SET utf8,
    `doc_name` VARCHAR(108) CHARACTER SET utf8,
    `doc_speciality` VARCHAR(28) CHARACTER SET utf8,
    `doc_department` VARCHAR(30) CHARACTER SET utf8,
    `Column_5` VARCHAR(28) CHARACTER SET utf8,
    `Column_6` VARCHAR(22) CHARACTER SET utf8,
    `Column_7` VARCHAR(3) CHARACTER SET utf8,
    `Column_8` INT
);
INSERT INTO Insert_Queries VALUES
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Joseph Thomas''','''Emergengy care''','''EMG Dept'')',NULL,NULL,NULL,NULL),
    ('(2','''Brian James''','''Dermatologist''','''Dermatology'')',NULL,NULL,NULL,NULL),
    ('(3','''Edward Shaw''','''ENT specialist''','''ENT'')',NULL,NULL,NULL,NULL),
    ('(4','''Charles Lion''','''EYE specialist''','''Ophthalmology'');',NULL,NULL,NULL,NULL),
    ('INSERT INTO Patient_info (p_id','p_name','p_address','doc_id)',NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Nash''','''117',' Seventh Street',' WestTown WT19 2YZ England''','1)',NULL,NULL),
    ('(2','''Isabella''','''111',' Ninth Street',' OldTown OT14 1YZ England''','3)',NULL,NULL),
    ('(3','''Jean''','''115',' Eleventh Street',' NewTown NT13 5YZ England''','4)',NULL,NULL),
    ('(4','''Leonard''','''101',' Second Street',' NewCity NC11 1YZ England''','2)',NULL,NULL),
    ('(5','''Richard''','''101',' Second Street',' NewCity NC11 2YZ England''','4);',NULL,NULL),
    ('INSERT INTO Patient_age (p_id','p_age)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','15)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','27)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','57)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','43);',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Patient_disease (p_id','p_disease)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Coughing and Fever'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','''Ear Pain'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','''Glaucoma'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','''Skin Infection'');',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Patient_gender (p_id','p_gender)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Male'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','''Female'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','''Female'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','''Male'');',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Patient_p_phone (p_phone','p_id)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(02012334577','1)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(02012344121','1)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(01211241233','2)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(01211714335','3)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(01211089213','3)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(01511532345','4)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(01517899123','4)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(01213115132','4);',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Appointment (apt_id','apt_description','apt_date_time','doc_id','p_id)',NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Patient has a serious condition on coughing and has mild fever.''','2020-12-25 12:35:00.00','1','1)',NULL,NULL,NULL),
    ('(2','''Patient needs extreame care for skin infections and other allergies.''','2020-12-27 11:10:00.00','2','4)',NULL,NULL,NULL),
    ('(3','''Patient has a severe  ear pain and suffers from nasal congestion most of the time.''','2020-12-28 12:30:00.00','3','2)',NULL,NULL,NULL),
    ('(4','''Patient has an serious eye infection and probably has Glaucoma that can damage the optic nerve of the eye.''','2020-12-24 10:30:00.00','4','3);',NULL,NULL,NULL),
    ('INSERT INTO Bill_total (bill_total_payment','bill_doctor_charge','bill_nursing_charge','bill_ward_charge','bill_lab_charge','bill_operation_charge)',NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(8000','2000','1000','1400','600','3000)',NULL,NULL),
    ('(4233','1000','500','433','500','1800)',NULL,NULL),
    ('(1200','300','100','200','100','500)',NULL,NULL),
    ('(3887','1000','600','500','200','1587);',NULL,NULL),
    ('INSERT INTO Bill (bill_id','p_id','bill_total_payment)',NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','2','4233)',NULL,NULL,NULL,NULL,NULL),
    ('(2','3','3887)',NULL,NULL,NULL,NULL,NULL),
    ('(3','1','1200)',NULL,NULL,NULL,NULL,NULL),
    ('(4','4','8000);',NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Bill_advance (bill_id','bill_advance_payment)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','600)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','400)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','440)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','350);',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Department (dept_id','dept_name','dept_employees','dept_head','dept_location)',NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''ENT''','47','''Robert James''','''South-End'')',NULL,NULL,NULL),
    ('(2','''Dermatology''','51','''Steven Nick''','''West-End'')',NULL,NULL,NULL),
    ('(3','''Ophthalmology''','31','''William Roger''','''North-End'')',NULL,NULL,NULL),
    ('(4','''EMG Dept''','24','''Steven Nick''','''South-East-End'');',NULL,NULL,NULL),
    ('INSERT INTO Lab (lab_id','lab_name','lab_timings','lab_tests_taken','lab_attendent','doc_id)',NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Lab-1''','''06:00:00.00 to 12:00:00.00''','32','''Edward''','2)',NULL,NULL),
    ('(2','''Lab-2''','''12:00:00.00 to 18:00:00.00''','21','''Mathew''','1)',NULL,NULL),
    ('(3','''Lab-3''','''18:00:00.00 to 00:00:00.00''','44','''George''','3)',NULL,NULL),
    ('(4','''Lab-4''','''00:00:00.00 to 06:00:00.00''','13','''David''','4);',NULL,NULL),
    ('INSERT INTO StaffMember_info (member_id','member_name','member_address','dept_id','Manages_member_id)',NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Emma''','''132',' My Street',' Bigtown BG23 4YZ England''','4','1)',NULL),
    ('(2','''Olivia''','''110',' New Street',' Newtown BG25 4YZ England''','3','2)',NULL),
    ('(3','''Emily''','''100',' First Street',' Oldtown OG21 3YZ England''','2','3)',NULL),
    ('(4','''Richard Hales''','''111',' Second Street',' NewCity NW23 7YZ England''','1','4)',NULL),
    ('(5','''Osman Nadeem''','''122',' Old Street',' NewHeaven NH27 7YZ England''','2','5)',NULL),
    ('(6','''Micheal John''','''133',' First Street',' OldValley OV26 8YZ England''','3','6)',NULL),
    ('(7','''Joseph Thomas''','''110',' New Street',' London LD25 1YZ England''','4','1)',NULL),
    ('(8','''Brian James''','''112',' New Street',' London LD25 1YZ England''','2','3)',NULL),
    ('(9','''Edward Shaw''','''114',' New Street',' London LD25 1YZ England''','1','5)',NULL),
    ('(10','''Charles Lion''','''115',' New Street',' London LD25 1YZ England''','3','2);',NULL),
    ('INSERT INTO Member_exp (member_experience','member_salary','member_designation','member_working_shifts)',NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(''9 months''','88720','''Nurse-I''','''06:00:00.00 to 15:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''11 months''','90560','''Nurse-II''','''14:00:00.00 to 22:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''15 months''','98910','''Nurse-III''','''20:00:00.00 to 07:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''7 months''','8720','''Receptionist-I''','''06:00:00.00 to 15:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''10 months''','9560','''Receptionist-II''','''14:00:00.00 to 22:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''17 months''','10910','''Receptionist-II''','''20:00:00.00 to 07:30:00.00'')',NULL,NULL,NULL,NULL),
    ('(''8 months''','104000','''Doc-I''','''06:00:00.00 to 15:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''13 months''','110560','''Doc-II''','''14:00:00.00 to 22:00:00.00'')',NULL,NULL,NULL,NULL),
    ('(''16 months''','112910','''Doc-II''','''20:00:00.00 to 07:30:00.00'')',NULL,NULL,NULL,NULL),
    ('(''25 months''','115050','''Doc-III''','''00:00:00.00 to 12:00:00.00'');',NULL,NULL,NULL,NULL),
    ('INSERT INTO StaffMember_ranking (member_id','member_experience)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''9 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2''11 months'')',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','''15 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','''7 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(5','''10 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(6','''17 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(7','''8 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(8','''13 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(9','''16 months'')',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(10','''25 months'');',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Ward (ward_id','ward_machines_available','ward_total_members','ward_type','ward_beds_available)',NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','12','33','''EMG Ward''','10)',NULL,NULL,NULL),
    ('(2','15','30','''Normal Ward''','15)',NULL,NULL,NULL),
    ('(3','11','35','''Critical Ward''','14)',NULL,NULL,NULL),
    ('(4','15','35','''Critical** Ward''','15);',NULL,NULL,NULL),
    ('INSERT INTO Patient_ward (ward_id','p_admit_date','p_discharge_date)',NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','2021-01-1','2021-01-9)',NULL,NULL,NULL,NULL,NULL),
    ('(2','2021-01-2','NULL)',NULL,NULL,NULL,NULL,NULL),
    ('(3','2021-01-1','NULL)',NULL,NULL,NULL,NULL,NULL),
    ('(4','2021-01-4','NULL);',NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Patient_stats (p_id','p_status','ward_id)',NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','''Normal''','1)',NULL,NULL,NULL,NULL,NULL),
    ('(2','''Normal''','2)',NULL,NULL,NULL,NULL,NULL),
    ('(3','''Critical''','3)',NULL,NULL,NULL,NULL,NULL),
    ('(4','''Critical**''','4);',NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Nurse (ward_id','p_id','member_id)',NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','1','3)',NULL,NULL,NULL,NULL,NULL),
    ('(2','2','1)',NULL,NULL,NULL,NULL,NULL),
    ('(3','3','2)',NULL,NULL,NULL,NULL,NULL),
    ('(4','4','3);',NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Receptionist (apt_id','member_id)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','4)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','5)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','6)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','6);',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Take_tests (p_id','lab_id)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','1)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','2)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','3)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','4);',NULL,NULL,NULL,NULL,NULL,NULL),
    ('INSERT INTO Is_A (doc_id','member_id)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('VALUES ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('(1','7)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(2','8)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(3','9)',NULL,NULL,NULL,NULL,NULL,NULL),
    ('(4','10);',NULL,NULL,NULL,NULL,NULL,NULL);
