CREATE TABLE IF NOT EXISTS SQL_CREATE_AND_ALTER (
    `CREATE_TABLE_Patient_info` VARCHAR(108) CHARACTER SET utf8,
    `Column_2` INT
);
INSERT INTO SQL_CREATE_AND_ALTER VALUES
    ('    p_id int NOT NULL UNIQUE',NULL),
    ('    p_name varchar(255) NOT NULL',NULL),
    ('    p_address varchar(255)',NULL),
    ('    doc_id int',NULL),
    ('    CONSTRAINT PK_Patient_info PRIMARY KEY (p_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Doctor (',NULL),
    ('    doc_id int NOT NULL UNIQUE',NULL),
    ('    doc_name varchar(255) NOT NULL',NULL),
    ('    doc_speciality varchar(255) NOT NULL',NULL),
    ('	doc_department varchar(255)',NULL),
    ('    CONSTRAINT PK_Doctor PRIMARY KEY (doc_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Appointment (',NULL),
    ('    apt_id int NOT NULL UNIQUE',NULL),
    ('    apt_description varchar(255) NOT NULL',NULL),
    ('    apt_date_time datetime NOT NULL',NULL),
    ('	doc_id int NOT NULL',NULL),
    ('	p_id int NOT NULL',NULL),
    ('    CONSTRAINT PK_Appointment PRIMARY KEY (apt_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Patient_disease (',NULL),
    ('    p_id int NOT NULL UNIQUE',NULL),
    ('    p_disease varchar(255) NOT NULL',NULL),
    ('    CONSTRAINT PK_Patient_disease PRIMARY KEY (p_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Patient_age (',NULL),
    ('    p_id int NOT NULL UNIQUE',NULL),
    ('    p_age int NOT NULL',NULL),
    ('    CONSTRAINT PK_Patient_age PRIMARY KEY (p_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Patient_gender (',NULL),
    ('    p_id int NOT NULL UNIQUE',NULL),
    ('    p_gender varchar(255) NOT NULL',NULL),
    ('    CONSTRAINT PK_Patient_gender PRIMARY KEY (p_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Patient_ward (',NULL),
    ('    ward_id int NOT NULL UNIQUE',NULL),
    ('    p_admit_date date NOT NULL',NULL),
    ('	p_discharge_date date ',NULL),
    ('    CONSTRAINT PK_Patient_ward PRIMARY KEY (ward_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Patient_stats (',NULL),
    ('    p_id int NOT NULL',NULL),
    ('    p_status varchar(255) NOT NULL',NULL),
    ('	ward_id int NOT NULL',NULL),
    ('    CONSTRAINT PK_Patient_stats PRIMARY KEY (p_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Patient_p_phone (',NULL),
    ('    p_phone int NOT NULL UNIQUE',NULL),
    ('	p_id int NOT NULL',NULL),
    ('    CONSTRAINT PK_Patient_p_phone PRIMARY KEY (p_phone)',NULL),
    (');',NULL),
    ('CREATE TABLE Ward (',NULL),
    ('    ward_id int NOT NULL UNIQUE',NULL),
    ('	ward_machines_available int ',NULL),
    ('	ward_total_members int NOT NULL',NULL),
    ('	ward_type varchar(255) NOT NULL',NULL),
    ('	ward_beds_available int ',NULL),
    ('    CONSTRAINT PK_Ward PRIMARY KEY (ward_id)',NULL),
    (');',NULL),
    ('CREATE TABLE StaffMember_info (',NULL),
    ('    member_id int NOT NULL UNIQUE',NULL),
    ('	member_name varchar(255) NOT NULL',NULL),
    ('	member_address varchar(255)',NULL),
    ('	dept_id int',NULL),
    ('	Manages_member_id int NOT NULL',NULL),
    ('    CONSTRAINT PK_StaffMember_info PRIMARY KEY (member_id)',NULL),
    (');',NULL),
    ('CREATE TABLE StaffMember_ranking(',NULL),
    ('    member_id int NOT NULL UNIQUE',NULL),
    ('	member_experience varchar(255) NOT NULL',NULL),
    ('    CONSTRAINT PK_StaffMember_ranking PRIMARY KEY (member_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Member_exp(',NULL),
    ('    member_experience varchar(255) NOT NULL',NULL),
    ('	member_salary int NOT NULL',NULL),
    ('	member_designation varchar(255)',NULL),
    ('	member_working_shifts varchar(255)',NULL),
    ('    CONSTRAINT PK_Member_exp PRIMARY KEY (member_experience)',NULL),
    (');',NULL),
    ('CREATE TABLE Department(',NULL),
    ('    dept_id int NOT NULL UNIQUE',NULL),
    ('	dept_name varchar(255) NOT NULL',NULL),
    ('	dept_employees int NOT NULL',NULL),
    ('	dept_head varchar(255) NOT NULL',NULL),
    ('	dept_location varchar(255)',NULL),
    ('    CONSTRAINT PK_Department PRIMARY KEY (dept_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Bill(',NULL),
    ('    bill_id int NOT NULL UNIQUE',NULL),
    ('	p_id int NOT NULL',NULL),
    ('    bill_total_payment int NOT NULL',NULL),
    ('    CONSTRAINT PK_Bill PRIMARY KEY (bill_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Bill_total(',NULL),
    ('    bill_total_payment int NOT NULL',NULL),
    ('	bill_doctor_charge int NOT NULL',NULL),
    ('	bill_nursing_charge int',NULL),
    ('	bill_ward_charge int',NULL),
    ('	bill_lab_charge int',NULL),
    ('	bill_operation_charge int',NULL),
    ('    CONSTRAINT PK_Bill_total PRIMARY KEY (bill_total_payment)',NULL),
    (');',NULL),
    ('CREATE TABLE Bill_advance(',NULL),
    ('    bill_id int NOT NULL UNIQUE',NULL),
    ('	bill_advance_payment int NOT NULL',NULL),
    ('    CONSTRAINT PK_Bill_advance PRIMARY KEY (bill_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Lab(',NULL),
    ('    lab_id int NOT NULL UNIQUE',NULL),
    ('	lab_name varchar(255) NOT NULL',NULL),
    ('	lab_timings varchar(255) NOT NULL',NULL),
    ('	lab_tests_taken int ',NULL),
    ('	lab_attendent varchar(255) NOT NULL',NULL),
    ('    doc_id int',NULL),
    ('    CONSTRAINT PK_Lab PRIMARY KEY (lab_id)',NULL),
    (');',NULL),
    ('CREATE TABLE Nurse(',NULL),
    ('    ward_id int NOT NULL',NULL),
    ('    p_id int NOT NULL',NULL),
    ('    member_id int NOT NULL',NULL),
    (');',NULL),
    ('CREATE TABLE Receptionist(',NULL),
    ('    apt_id int NOT NULL',NULL),
    ('    member_id int NOT NULL',NULL),
    (');',NULL),
    ('CREATE TABLE Take_tests(',NULL),
    ('    p_id int NOT NULL',NULL),
    ('    lab_id int NOT NULL',NULL),
    (');',NULL),
    ('CREATE TABLE Is_A(',NULL),
    ('    doc_id int NOT NULL UNIUQE',NULL),
    ('    member_id int NOT NULL UNIQUE',NULL),
    (');',NULL),
    ('---------------------------------------------------------------------',NULL),
    ('ALTER TABLE Patient_info',NULL),
    ('ADD CONSTRAINT FK_PatientDoctor',NULL),
    ('FOREIGN KEY (doc_id) REFERENCES Doctor(doc_id);',NULL),
    ('ALTER TABLE Patient_info',NULL),
    ('ADD CONSTRAINT df_p_name',NULL),
    ('DEFAULT ''Patient'' For p_name;',NULL),
    ('ALTER TABLE Doctor',NULL),
    ('ADD CONSTRAINT df_doc_name',NULL),
    ('DEFAULT ''Doctor'' For doc_name;',NULL),
    ('ALTER TABLE Patient_gender',NULL),
    ('ADD CONSTRAINT df_p_gender',NULL),
    ('DEFAULT ''N/A'' For p_gender;',NULL),
    ('ALTER TABLE Appointment',NULL),
    ('ADD CONSTRAINT FK_AppointmentDoctor',NULL),
    ('FOREIGN KEY (doc_id) REFERENCES Doctor(doc_id)',NULL),
    (';',NULL),
    ('ALTER TABLE Appointment',NULL),
    ('ADD CONSTRAINT FK_AppointmentPatient',NULL),
    ('FOREIGN KEY (p_id) REFERENCES Patient_info(p_id)',NULL),
    (';',NULL),
    ('ALTER TABLE Patient_stats',NULL),
    ('ADD CONSTRAINT FK_Patient_ward FOREIGN KEY (ward_id) REFERENCES Patient_ward(ward_id)',NULL),
    (';',NULL),
    ('ALTER TABLE Patient_stats',NULL),
    ('ADD CONSTRAINT FK_Patient_Oward FOREIGN KEY (ward_id) REFERENCES Ward(ward_id)',NULL),
    (';',NULL),
    ('ALTER TABLE StaffMember_info',NULL),
    ('ADD CONSTRAINT FK_StaffMember_dept FOREIGN KEY (dept_id) REFERENCES Department(dept_id)',NULL),
    (';',NULL),
    ('ALTER TABLE StaffMember_info',NULL),
    ('ADD CONSTRAINT FK_StaffMember_manages FOREIGN KEY (Manages_member_id) REFERENCES StaffMember_info(member_id)',NULL),
    (';',NULL),
    ('ALTER TABLE StaffMember_ranking',NULL),
    ('ADD CONSTRAINT FK_StaffMember_exp FOREIGN KEY (member_experience) REFERENCES Member_exp(member_experience)',NULL),
    (';',NULL),
    ('ALTER TABLE Bill',NULL),
    ('ADD CONSTRAINT FK_Bill_patient FOREIGN KEY (p_id) REFERENCES Patient_info(p_id)',NULL),
    (';',NULL),
    ('ALTER TABLE Bill',NULL),
    ('ADD CONSTRAINT FK_Bill_total FOREIGN KEY (bill_total_payment) REFERENCES Bill_total(bill_total_payment)',NULL),
    (';',NULL),
    ('ALTER TABLE Lab',NULL),
    ('ADD CONSTRAINT FK_Lab_reportDoc FOREIGN KEY (doc_id) REFERENCES Doctor(doc_id)',NULL),
    (';',NULL),
    ('ALTER TABLE Patient_age',NULL),
    ('ADD CHECK (p_age>0);',NULL),
    ('ALTER TABLE Bill',NULL),
    ('ADD CHECK (bill_total_payment>0);',NULL),
    ('ALTER TABLE Bill_advance',NULL),
    ('ADD CHECK (bill_advance_payment>0);',NULL),
    ('ALTER TABLE Nurse',NULL),
    ('ADD CONSTRAINT FK_Nurse_ward ',NULL),
    ('FOREIGN KEY (ward_id) ',NULL),
    ('REFERENCES Ward(ward_id);',NULL),
    ('ALTER TABLE Nurse',NULL),
    ('ADD CONSTRAINT FK_Nurse_patient ',NULL),
    ('FOREIGN KEY (p_id) ',NULL),
    ('REFERENCES Patient_info(p_id);',NULL),
    ('ALTER TABLE Nurse',NULL),
    ('ADD CONSTRAINT FK_Nurse_id ',NULL),
    ('FOREIGN KEY (member_id) ',NULL),
    ('REFERENCES StaffMember_info(member_id);',NULL),
    ('ALTER TABLE Receptionist',NULL),
    ('ADD CONSTRAINT FK_Receptionist_apt',NULL),
    ('FOREIGN KEY (apt_id) ',NULL),
    ('REFERENCES Appointment(apt_id);',NULL),
    ('ALTER TABLE Receptionist',NULL),
    ('ADD CONSTRAINT FK_Receptionist_id ',NULL),
    ('FOREIGN KEY (member_id) ',NULL),
    ('REFERENCES StaffMember_info(member_id);',NULL),
    ('ALTER TABLE Take_tests',NULL),
    ('ADD CONSTRAINT FK_Take_tests_patient ',NULL),
    ('FOREIGN KEY (p_id) ',NULL),
    ('REFERENCES Patient_info(p_id);',NULL),
    ('ALTER TABLE Take_tests',NULL),
    ('ADD CONSTRAINT FK_Take_tests_lab ',NULL),
    ('FOREIGN KEY (lab_id) ',NULL),
    ('REFERENCES Lab(lab_id);',NULL),
    ('ALTER TABLE Is_A',NULL),
    ('ADD CONSTRAINT FK_Is_A_doc ',NULL),
    ('FOREIGN KEY (doc_id) ',NULL),
    ('REFERENCES Doctor(doc_id);',NULL),
    ('ALTER TABLE Is_A',NULL),
    ('ADD CONSTRAINT FK_Is_A_member ',NULL),
    ('FOREIGN KEY (member_id) ',NULL);
